server : 
  host : "localhost"
  port : "8000"
resources : 
  - name : server1 
    endpoint : /server1
    url : "http://localhost:9001"
  - name : server2 
    endpoint : /server2
    url : "http://localhost:9002"
  - name : server3 
    endpoint : /server3
    url : "http://localhost:9003"


